# Generated by Django 5.0.6 on 2024-06-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_pdf',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='fb42fb', max_length=6),
        ),
    ]
