# Generated by Django 5.0.6 on 2024-06-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0006_post_pdf_price_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='bd437d', max_length=6),
        ),
        migrations.AlterField(
            model_name='post_pdf',
            name='posted_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
