# Generated by Django 5.0.6 on 2024-05-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0007_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='f15993', max_length=6),
        ),
    ]
