# Generated by Django 5.0.6 on 2024-05-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0008_alter_customuser_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='75ae39', max_length=6),
        ),
    ]
