# Generated by Django 5.0.6 on 2024-06-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0010_alter_otptoken_otp_code_alter_post_pdf_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(choices=[('Select Your Bank', 'Select Your Bank'), ('SEA Bank', 'SEA Bank'), ('BPI Bank', 'BPI Bank'), ('KOMO Bank', 'KOMO Bank'), ('Gcash account', 'Gcash account'), ('Wells Fargo Bank', 'Well Fargo Bank'), ('U.S. Bank', 'U.S. Bank'), ('Citi Bank', 'Citi Bank'), ('PNC Financial Services Group, Inc', 'PNC Financial Services Group, Inc'), ('DBS Group Holdings Ltd', 'DBS Group Holdings Ltd'), ('Ecobank Nigeria', 'Ecobank Nigeria'), ('Oversea-Chinese Banking Corporation', 'Oversea-Chinese Banking Corporation'), ('United Overseas Bank Ltd', 'United Overseas Bank Ltd'), ('Hongkong Shanghai Banking Corporation Limited', 'Hongkong Shanghai Banking Corporation Limited'), ('Royal Bank of Canada', 'Royal Bank of Canada'), ('Toronto-Dominion Bank', 'Toronto-Dominion Bank'), ('Bank of Nova Scotia', 'Bank of Nova Scotia'), ('Bank of Montreal', 'Bank of Montreal'), ('Canadian Imperial Bank of Commerce', 'Canadian Imperial Bank of Commerce'), ('Bangkok Bank', 'Bangkok Bank'), ('CIMB Thai Bank', 'CIMB Thai Bank'), ('Tisco Bank', 'Tisco Bank'), ('SCB account', 'SCB account'), ('Lloyds Bank', 'Lloyds Bank'), ('Royal Bank', 'Royal Bank'), ('Barclays account', 'Barclays account'), ('Emirates NBD Bank', 'Emirates NBD Bank'), ('Dubai Islamic Bank', 'Dubai Islamic Bank'), ('Mashreq Bank', 'Mashreq Bank'), ('Union National Bank', 'Union National Bank')], max_length=50),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b9ba8c', max_length=6),
        ),
    ]
