# Generated by Django 5.0.6 on 2024-05-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0011_alter_customuser_bank_name_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(choices=[('Select Your Bank', 'Select Your Bank'), ('Access Bank Plc', 'Access Bank Plc'), ('Fidelity Bank Plc', 'Fidelity Bank Plc'), ('First City Monument Bank Limited', 'First City Monument Bank Limited'), ('First Bank of Nigeria Limited', 'First Bank of Nigeria Limited'), ('Guaranty Trust Holding Company Plc', 'Guaranty Trust Holding Company Plc'), ('Union Bank of Nigeria Plc', 'Union Bank of Nigeria Plc'), ('United Bank for Africa Plc', 'United Bank for Africa Plc'), ('Zenith Bank Plc', 'Zenith Bank Plc'), ('Citibank Nigeria Limited', 'Citibank Nigeria Limited'), ('Ecobank Nigeria', 'Ecobank Nigeria'), ('Heritage Bank Plc', 'Heritage Bank Plc'), ('Keystone Bank Limited', 'Keystone Bank Limited'), ('Optimus Bank Limited', 'Optimus Bank Limited'), ('Polaris Bank Limited', 'Polaris Bank Limited'), ('Stanbic IBTC Bank Plc', 'Stanbic IBTC Bank Plc'), ('Standard Chartered', 'Standard Chartered'), ('Sterling Bank Plc', 'Sterling Bank Plc'), ('Titan Trust Bank', 'Titan Trust Bank'), ('Unity Bank Plc', 'Unity Bank Plc'), ('Wema Bank Plc', 'Wema Bank Plc')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='692a85', max_length=6),
        ),
    ]
