# Generated by Django 5.0.6 on 2024-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0013_useramount_currency_alter_customuser_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a1c077', max_length=6),
        ),
        migrations.AlterField(
            model_name='useramount',
            name='currency',
            field=models.CharField(blank=True, choices=[('&#163;', '&#163;'), ('&#36;', '&#36;'), ('&#8369;', '&#8369;'), ('&#3647;', '&#3647;'), ('AED', 'AED'), ('&#8371;', '&#8371;'), ('ZAR', 'ZAR')], default='&#36', max_length=30, null=True),
        ),
    ]
