# Generated by Django 5.0.6 on 2024-06-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0015_alter_otptoken_otp_code_alter_useramount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c151e4', max_length=6),
        ),
        migrations.AlterField(
            model_name='useramount',
            name='currency',
            field=models.CharField(blank=True, choices=[('£', '£'), ('&#36;', '&#36;'), ('&#8369;', '&#8369;'), ('&#3647;', '&#3647;'), ('AED', 'AED'), ('&#8371;', '&#8371;'), ('ZAR', 'ZAR')], default='&#36', max_length=30, null=True),
        ),
    ]
