# Generated by Django 5.0.6 on 2024-06-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0024_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='7c581d', max_length=6),
        ),
        migrations.AlterField(
            model_name='post_pdf',
            name='pdf_file',
            field=models.FileField(upload_to='https://foundevermedia.s3.amazonaws.com/static/'),
        ),
    ]
