# Generated by Django 5.0.6 on 2024-06-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0026_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='ab1e77', max_length=6),
        ),
        migrations.AlterField(
            model_name='post_pdf',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
