# Generated by Django 5.0.6 on 2024-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0027_alter_otptoken_otp_code_alter_post_pdf_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_pdf',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='post_pdf',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='4665a9', max_length=6),
        ),
    ]
