# Generated by Django 5.0.6 on 2024-06-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0028_remove_post_pdf_pdf_file_post_pdf_pdf_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='76f0d2', max_length=6),
        ),
        migrations.AlterField(
            model_name='post_pdf',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
