# Generated by Django 5.0.6 on 2024-07-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0029_alter_otptoken_otp_code_alter_post_pdf_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='01c64e', max_length=6),
        ),
    ]
