# Generated by Django 5.0.6 on 2024-08-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0032_alter_customuser_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='114ea2', max_length=6),
        ),
    ]
